alertmanager:
  enabled: false

grafana:
  enabled: false

prometheus:
  prometheusSpec:
    retention: 2d
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 1Gi
